name: Deploy Java EE App

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build WAR
        run: mvn clean package

      - name: Clean previous Tomcat deployment
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            rm -rf /opt/tomcat/webapps/IntelliprimeWeb
            rm -f /opt/tomcat/webapps/IntelliprimeWeb.war

      - name: Copy WAR to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "target/*.war"
          target: "/opt/tomcat/webapps/"

      - name: Restart Tomcat
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /opt/tomcat/bin
            ./shutdown.sh || true
            sleep 5
            ./startup.sh